"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# The hardcoded fallback only ever runs locally outside Docker (`python
# manage.py runserver` with no .env) -- every other environment, including
# docker-compose, sets POKER_SECRET_KEY explicitly (see .env.example).
SECRET_KEY = os.environ.get(
    'POKER_SECRET_KEY', 'django-insecure-rafhjuw%!18glp!(z8g+9y5ty=lo)_@^tq7703ilhl*vrj#4(g'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('POKER_DEBUG', 'true').lower() == 'true'

ALLOWED_HOSTS = [h for h in os.environ.get('POKER_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if h]


# Application definition

INSTALLED_APPS = [
    'daphne',
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'table',
    'accounts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'config.asgi.application'

# 127.0.0.1 is correct for every process running directly on the host (how
# this has run all along); inside docker-compose, Redis is a separate
# container reachable only by its service name, so POKER_REDIS_HOST=redis
# overrides this there (see docker-compose.yml / .env.example).
POKER_REDIS_HOST = os.environ.get('POKER_REDIS_HOST', '127.0.0.1')
POKER_REDIS_PORT = int(os.environ.get('POKER_REDIS_PORT', '6379'))

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [(POKER_REDIS_HOST, POKER_REDIS_PORT)],
        },
    },
}

# Same Redis instance as the channel layer above -- broker holds pending task
# messages, result backend holds their return values once a worker finishes.
CELERY_BROKER_URL = f'redis://{POKER_REDIS_HOST}:{POKER_REDIS_PORT}/0'
CELERY_RESULT_BACKEND = f'redis://{POKER_REDIS_HOST}:{POKER_REDIS_PORT}/0'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Env-var overrides so the same settings work against a local Homebrew
# Postgres (no password by default) and a real deployment later.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POKER_DB_NAME', 'pokerbot'),
        'USER': os.environ.get('POKER_DB_USER', ''),
        'PASSWORD': os.environ.get('POKER_DB_PASSWORD', ''),
        'HOST': os.environ.get('POKER_DB_HOST', 'localhost'),
        'PORT': os.environ.get('POKER_DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Structured logging (structlog) -- every log call across consumers.py,
# tasks.py, and registry.py goes through this pipeline so entries come out
# as one JSON object per line, machine-parseable by log aggregators instead
# of ad-hoc printf-style strings.
import logging
import structlog

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}

structlog.configure(
    processors=[
        structlog.contextvars.merge_contextvars,
        structlog.processors.add_log_level,
        structlog.processors.TimeStamper(fmt='iso'),
        structlog.processors.JSONRenderer(),
    ],
    wrapper_class=structlog.make_filtering_bound_logger(logging.INFO),
    logger_factory=structlog.PrintLoggerFactory(),
    cache_logger_on_first_use=True,
)
