# Generated by Django 5.2.17 on 2026-10-02 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('table_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Hand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.JSONField()),
                ('pot', models.IntegerField()),
                ('results', models.JSONField()),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='table.table')),
            ],
        ),
    ]
