# Generated by Django 5.2.17 on 2026-10-03 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hand',
            name='hand_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='hand',
            constraint=models.UniqueConstraint(fields=('table', 'hand_number'), name='unique_hand_number_per_table'),
        ),
    ]
